---
title: "shinyapp"
output: html_document
date: "2022-07-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#install packages
library(shiny)
library(dqshiny)
library(shinythemes)
library(dplyr)
library(gbm)
library(xgboost)
library(tibble)
library(caret)
```

```{r}
#bring in needed files
model <- readRDS("model.rds")
pitch_max <- readRDS("data/pitch_max.rds")
bat_max <- readRDS("data/bat_max.rds")
sprint_max <- readRDS("data/sprint_max.rds")
stand_bat <- readRDS("data/stand_bat.rds")
p_throw <- readRDS("data/p_throw.rds")
input_df <- readRDS("data/input_df.rds")

bat_names <- as.list(bat_max$hitter_name)
pit_names <- as.list(pitch_max$pitcher_name)
run_names <- as.list(sprint_max$player_name)

```


## User Interface

```{r}
ui <- fluidPage(theme = shinytheme("cerulean"),

    # Application title
    titlePanel("Should You Sacrifice Bunt?"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            selectInput("outs_when_up", label = "Outs",
                        choices = list(0, 1),
                        selected = 0),
            autocomplete_input(id = "bat",
                         label = "Batter",
                         options = bat_names,
                         max_options = 10,
                         value = "Leury Garcia"),
            autocomplete_input(id = "pitch",
                         label = "Pitcher",
                         options = pit_names,
                         max_options = 10,
                         value = "Gerrit Cole"),
            autocomplete_input(id = "on1b",
                         label = "On First",
                         options = run_names,
                         max_options = 10),
            autocomplete_input("on2b",
                         label = "On Second",
                         options = run_names,
                         max_options = 10,
                         value = "Josh Harrison"),
            # autocomplete_input("on3b",
            #              label = "On Third",
            #              options = run_names,
            #              max_options = 10),
            autocomplete_input("deck",
                         label = "On Deck",
                         options = bat_names,
                         max_options = 10,
                         value = "Tim Anderson"),
            autocomplete_input("hole",
                         label = "In the hole",
                         options = bat_names,
                         max_options = 10,
                         value = "Yoan Moncada"),
            
            actionButton("submitbutton", "Submit", 
                         class = "btn btn-primary"),
            actionButton("reset", "Clear", 
                         class = "btn btn-primary")
        ),

        # Show a plot of the generated distribution
        mainPanel(
           tags$label(h3('Output')),
        #   verbatimTextOutput('contents'),
           tableOutput('tabledata')
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    #Input data
  datasetInput <- reactive({
    
#    validate(
#      need(is.na(input$on1b) && is.na(input$on2b), "Please enter base runner.")
#    )
    

    inp <- pitch_max %>% filter(pitcher_name == input$pitch) %>%
      left_join(p_throw, by = "pitcher") %>%
      cbind(filter(bat_max, hitter_name == input$bat)%>%
              rename_with( ~ paste0(.x, ".x")) %>%
              rename(batter = batter.x)) %>%
      left_join(stand_bat, by = c("batter", "p_throws")) %>%
      left_join(sprint_max, by = c("batter" = "player_id")) %>%
      rename(sprint_speed_bat = sprint_speed) %>%
      mutate(filter(bat_max, hitter_name == input$deck) %>%
               rename_with( ~ paste0(.x, ".y"))) %>%
      mutate(sprint_speed_1b = ifelse(is.na(input$on1b), NA, as.numeric(filter(sprint_max, player_name == input$on1b)[2]))) %>%
      mutate(sprint_speed_2b = ifelse(is.na(input$on2b), NA, as.numeric(filter(sprint_max, player_name == input$on2b)[2]))) %>%
#      mutate(sprint_speed_3b = ifelse(is.na(input$on3b), NA, as.numeric(filter(sprint_max, player_name == input$on3b)[2]))) %>%
      mutate(sprint_speed_3b = NA) %>%
      mutate(outs_when_up = as.numeric(input$outs_when_up)) %>%
      ungroup()
    
    inp2 <- input_df(inp) %>%
      select(-c(batter,hitter_name.x, pitcher,player_name,pitcher_name,hitter_name.y, batter.y, stand, p_throws)) %>%
      mutate(game_year.x = "2022") %>%
      select(c(game_year.x, outs_when_up, BF_cum_tot.x, cum_b_k_rate.x, cum_b_bb_rate.x, BF_cum_hand, cum_b_k_rate_hand,
               cum_b_bb_rate_hand, BF_rol_tot.x, rol_b_k_rate.x, rol_b_bb_rate.x, BF_rol_hand, rol_b_k_rate_hand,
               rol_b_bb_rate_hand, wRC_cum_tot.x, wRC_cum_hand, wRC_rol_tot.x, wRC_rol_hand, FIP_cum_tot, cum_p_k_rate,
               cum_p_bb_rate, FIP_cum_hand, cum_p_k_rate_hand, cum_p_bb_rate_hand, FIP_rol_tot, rol_p_k_rate, rol_p_bb_rate,
               FIP_rol_hand, rol_p_k_rate_hand, rol_p_bb_rate_hand, sprint_speed_bat, BF_cum_tot.y, cum_b_k_rate.y, cum_b_bb_rate.y,
               BF_cum_hand_od, cum_b_k_rate_hand_od, cum_b_bb_rate_hand_od, BF_rol_tot.y, rol_b_k_rate.y, rol_b_bb_rate.y,
               BF_rol_hand_od, rol_b_k_rate_hand_od, rol_b_bb_rate_hand_od, wRC_cum_tot.y, wRC_cum_hand_od, wRC_rol_tot.y,
               wRC_rol_hand_od, sprint_speed_1b, sprint_speed_2b, sprint_speed_3b))
    
    
    out <- pitch_max %>% filter(pitcher_name == input$pitch) %>%
      left_join(p_throw, by = "pitcher") %>%
      cbind(filter(bat_max, hitter_name == input$deck)%>%
              rename_with( ~ paste0(.x, ".x")) %>%
              rename(batter = batter.x)) %>%
      left_join(stand_bat, by = c("batter", "p_throws")) %>%
      left_join(sprint_max, by = c("batter" = "player_id")) %>%
      rename(sprint_speed_bat = sprint_speed) %>%
      mutate(filter(bat_max, hitter_name == input$hole) %>%
               rename_with( ~ paste0(.x, ".y"))) %>%
      mutate(sprint_speed_1b = NA) %>%
      mutate(sprint_speed_2b = ifelse(is.na(input$on1b), NA, as.numeric(filter(sprint_max, player_name == input$on1b)[2]))) %>%
      mutate(sprint_speed_3b = ifelse(is.na(input$on2b), NA, as.numeric(filter(sprint_max, player_name == input$on2b)[2]))) %>%
      mutate(outs_when_up = as.numeric(input$outs_when_up) + 1) %>%
      ungroup()
    
    out2 <- input_df(out) %>%
      select(-c(batter,hitter_name.x,pitcher,pitcher_name,player_name, batter.y,hitter_name.y, stand, p_throws)) %>%
      mutate(game_year.x = "2022") %>%
      select(c(game_year.x, outs_when_up, BF_cum_tot.x, cum_b_k_rate.x, cum_b_bb_rate.x, BF_cum_hand, cum_b_k_rate_hand,
               cum_b_bb_rate_hand, BF_rol_tot.x, rol_b_k_rate.x, rol_b_bb_rate.x, BF_rol_hand, rol_b_k_rate_hand,
               rol_b_bb_rate_hand, wRC_cum_tot.x, wRC_cum_hand, wRC_rol_tot.x, wRC_rol_hand, FIP_cum_tot, cum_p_k_rate,
               cum_p_bb_rate, FIP_cum_hand, cum_p_k_rate_hand, cum_p_bb_rate_hand, FIP_rol_tot, rol_p_k_rate, rol_p_bb_rate,
               FIP_rol_hand, rol_p_k_rate_hand, rol_p_bb_rate_hand, sprint_speed_bat, BF_cum_tot.y, cum_b_k_rate.y, cum_b_bb_rate.y,
               BF_cum_hand_od, cum_b_k_rate_hand_od, cum_b_bb_rate_hand_od, BF_rol_tot.y, rol_b_k_rate.y, rol_b_bb_rate.y,
               BF_rol_hand_od, rol_b_k_rate_hand_od, rol_b_bb_rate_hand_od, wRC_cum_tot.y, wRC_cum_hand_od, wRC_rol_tot.y,
               wRC_rol_hand_od, sprint_speed_1b, sprint_speed_2b, sprint_speed_3b))
    
    set.seed(3535)
    
    inp3 <- xgb.DMatrix(data = data.matrix(inp2))
    out3 <- xgb.DMatrix(data = data.matrix(out2))
    
    pred1 <- predict(model, inp3)
    pred2 <- predict(model, out3)
    
    # if(pred1 >= pred2){
    #       print(paste("The expected runs created in your current sitation is", round(pred1,4),
    #                   "The expected runs created from a successful bunt is", round(pred2,4),
    #                   "We recommend NOT bunting"))
    #     } else if(pred2 > pred1){
    #       print(paste("The expected runs created in your current sitation is", pred1, "..",
    #                   "The expected runs created from a successful bunt is", pred2, ".",
    #                   "We recommend bunting."))
    #     }
    
    df_output <- tibble("Expected Runs - No Bunt" = pred1,
                          "Expected Runs - Bunt" = pred2,
                          Recommendation = ifelse(pred1 >= pred2, "Don't Bunt", "Bunt"))
    
    print(df_output)
    
  })
  
  output$tabledata <- renderTable({
    if (input$submitbutton > 0) {
      isolate(datasetInput())
    }
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```



